---
- name: Create L2VNI
  hosts: nxos_vteps
  gather_facts: no

  tasks:
    - name: Add L2VNI to Overlay
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: 200STUDENT_ID
        multicast_group: 239.239.239.100
        suppress_arp: true

    - name: Add L2VNI to EVPN
      nxos_evpn_vni:
        vni: 200STUDENT_ID
        route_distinguisher: auto
        route_target_both: auto
