---
- name: Destroy L2VNI
  hosts: nxos_vteps
  gather_facts: no

  tasks:
    - name: Remove L2VNI from Overlay
      nxos_vxlan_vtep_vni:
        interface: nve1
        vni: 200STUDENT_ID
        state: absent
