---
- name: Configure streaming telemetry destinations
  hosts: nxos_vteps
  gather_facts: no

  tasks:
    - name: Configure destinations
      nxos_config:
        src: 11.telemetry_cli.j2
      vars:
        my_destination_group: STUDENT_ID
