---

ansible_user: vagrant
ansible_password: vagrant
#ansible_ssh_port: 1022
ansible_network_os: nxos
ansible_connection: network_cli
#[all:vars]
ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
